# Generated by Django 4.0.4 on 2022-08-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rich', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
