# Generated by Django 4.0.4 on 2022-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rich', '0002_rename_rooms_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='messages',
            field=models.TextField(default=''),
        ),
    ]
